import type { Metadata } from "next";
import { Bricolage_Grotesque, Inter } from "next/font/google";
import "./globals.css";

const interSans = Inter({
    variable: "--font-inter-sans",
    subsets: ["latin"],
});

const bricolageGrotesqueSans = Bricolage_Grotesque({
    variable: "--font-bricolage-grotesque-sans",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Speezy",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={`${interSans.variable} ${bricolageGrotesqueSans.variable} antialiased`}>{children}</body>
        </html>
    );
}
