name: Changelog
on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+*"
jobs:
  Create-Changelog:
    name: Create Changelog
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Get release number
        id: get_release_number
        run: echo "RELEASE_NUMBER=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - uses: ardalanamini/auto-changelog@v4
        id: changelog
        name: Generate Changelog
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          default-commit-type: Other Changes
          release-name: ${{ steps.get_release_number.outputs.RELEASE_NUMBER }}
