name: Preview Deployment
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

on:
  push:
    branches:
      - main
    paths-ignore:
      - ".github/**"
      - "scripts/**"
      - "**/*.md"
      - "Dockerfile"
      - ".dockerignore"
      - ".gitignore"
      - "prettierrc"
      - "eslint.config.*"
      - "LICENSE*"
      - ".yarnrc.yml"
  workflow_run:
    workflows: ["Production Release"] # also run after production release to use the correct `RELEASE_NAME`
    types:
      - completed

jobs:
  test:
    name: Test
    permissions:
      contents: read
    uses: ./.github/workflows/test.yml

  deploy:
    name: Deploy Preview
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout source code
        uses: actions/checkout@v5

      - name: Enable Corepack
        run: corepack enable

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: 24

      - name: Install Dependencies
        run: yarn install --immutable

      - name: Restore Next.js Build Cache
        uses: actions/cache@v4
        with:
          path: .next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/yarn.lock') }}-${{ hashFiles('**/*.[jt]s', '**/*.[jt]sx') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('**/yarn.lock') }}-

      - name: Disable Telemetry
        run: |
          yarn vercel telemetry disable
          npx next telemetry disable

      - name: Pull Vercel Environment Information
        run: yarn vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

      - name: Build Project Artifacts
        run: yarn vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy Project Artifacts to Vercel
        run: yarn vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
